title: Blog
description: My Personal Stack Problems
author: Raisler Voigt
github: https://github.com/raisler
about: I'm problem solver in data field
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/raisler-voigt7/?locale=en_US"
    - icon: fa-github
      link: "https://github.com/raisler"

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/

url: "https://raisler.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
